"""
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
import sys
import os

def main():
    s = "abcd"
    t = "abcde"

    s = list(set(s))
    t = list(set(t))
    s.sort()
    t.sort()
    arr = []

    for i in s:
        for j in t:
            if(i)

""" 
    s = list(set(s))
    t = list(set(t))
    s.sort()
    t.sort()
    arr = []

    for i in t:
        if i not in s:
            arr.append(i)
    return "".join(arr)
"""


"""
    s = list(s)
    t = list(t)
    s.sort()
    t.sort()
    arr = []
    for i in t:
        for j in s:
"""

if __name__ == '__main__':
    main()